const router=require('express').Router();const {auth,role}=require('../middleware/auth');const Product=require('../models/Product');const Order=require('../models/Order');const User=require('../models/User');const Coupon=require('../models/Coupon');const Banner=require('../models/Banner');const ReturnRequest=require('../models/ReturnRequest');const SupportTicket=require('../models/SupportTicket');const Inventory=require('../models/InventoryTransaction');const Category=require('../models/Category');const Brand=require('../models/Brand');const Notification=require('../models/Notification');const ProductChat=require('../models/ProductChat');const Alert=require('../utils/alerts');const audit=require('../utils/audit');
router.use(auth,role('admin'));
router.get('/stats',async(req,res)=>{const [users,products,orders,revenue,pending,low,returns,tickets,productChats]=await Promise.all([User.countDocuments({role:'customer'}),Product.countDocuments({deletedAt:{$exists:false}}),Order.countDocuments(),Order.aggregate([{$match:{paymentStatus:{$in:['PAID','COD']}}},{$group:{_id:null,v:{$sum:'$total'}}}]),Order.countDocuments({status:{$in:['Payment Pending','Confirmed','Processing','Packed','Shipped','Out for Delivery']}}),Product.countDocuments({stock:{$lte:5},deletedAt:{$exists:false}}),ReturnRequest.countDocuments({status:{$nin:['REFUNDED','REJECTED','REPLACED']}}),SupportTicket.countDocuments({status:{$in:['OPEN','IN_PROGRESS']}}),ProductChat.countDocuments({unreadForAdmin:true})]);res.json({users,products,orders,revenue:revenue[0]?.v||0,pending,lowStock:low,returns,tickets,productChats})});
router.get('/analytics',async(req,res)=>{const sales=await Order.aggregate([{$match:{createdAt:{$gte:new Date(Date.now()-30*86400000)}}},{$group:{_id:{$dateToString:{format:'%Y-%m-%d',date:'$createdAt'}},orders:{$sum:1},revenue:{$sum:'$total'}}},{$sort:{_id:1}}]);const cats=await Product.aggregate([{$group:{_id:'$category',products:{$sum:1},stock:{$sum:'$stock'}}},{$sort:{products:-1}},{$limit:10}]);res.json({sales,categories:cats})});
router.get('/products',async(req,res)=>res.json(await Product.find().sort({createdAt:-1}).limit(500)));
router.post('/products',async(req,res)=>{try{const b={...req.body};b.name=String(b.name||'').trim();if(!b.name)return res.status(400).json({message:'Product name required'});b.slug=String(b.slug||b.name).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString().slice(-5);b.sku=String(b.sku||('SV-'+Date.now())).trim().toUpperCase();b.price=Number(b.price||0);b.mrp=Number(b.mrp||b.price||0);b.stock=Number(b.stock||0);b.discount=b.mrp>b.price?Math.round((b.mrp-b.price)*100/b.mrp):Number(b.discount||0);b.images=b.images||{};if(typeof b.images.main!=='string')b.images.main='';const x=await Product.create(b);await audit(req,'CREATE_PRODUCT','Product',x._id,null,x.toObject());res.status(201).json(x)}catch(e){res.status(400).json({message:e.message})}});
router.patch('/products/:id',async(req,res)=>{delete req.body._id;if(req.body.price!==undefined)req.body.price=Number(req.body.price);if(req.body.mrp!==undefined)req.body.mrp=Number(req.body.mrp);if(req.body.stock!==undefined)req.body.stock=Number(req.body.stock);if(req.body.price!==undefined||req.body.mrp!==undefined){const cur=await Product.findById(req.params.id).lean();const price=Number(req.body.price!==undefined?req.body.price:cur?.price||0),mrp=Number(req.body.mrp!==undefined?req.body.mrp:cur?.mrp||price);req.body.discount=mrp>price?Math.round((mrp-price)*100/mrp):0;}const old=await Product.findById(req.params.id);if(!old)return res.status(404).json({message:'Not found'});const beforeStock=old.stock;const beforeDoc=old.toObject();Object.assign(old,req.body);await old.save();await Alert(old,beforeDoc);if(req.body.stock!==undefined&&Number(beforeStock)!==Number(old.stock))await Inventory.create({product:old._id,admin:req.user._id,type:'ADJUST',qty:Number(old.stock)-Number(beforeStock),before:beforeStock,after:old.stock,reason:'Admin stock edit'});await audit(req,'UPDATE_PRODUCT','Product',old._id,beforeDoc,old.toObject());res.json(old)});
router.delete('/products/:id',async(req,res)=>{const x=await Product.findByIdAndUpdate(req.params.id,{deletedAt:new Date()},{new:true});await audit(req,'SOFT_DELETE_PRODUCT','Product',req.params.id,null,x?.toObject());res.json({message:'Archived'})});
router.get('/orders',async(req,res)=>res.json(await Order.find().populate('user','name email').sort({createdAt:-1}).limit(300)));
router.patch('/orders/:id/status',async(req,res)=>{const allowed=['Confirmed','Processing','Packed','Shipped','Out for Delivery','Delivered','Cancelled','Return Requested','Returned','Refund Initiated','Refunded'];if(!allowed.includes(req.body.status))return res.status(400).json({message:'Invalid status'});const o=await Order.findById(req.params.id);if(!o)return res.status(404).json({message:'Order not found'});o.status=req.body.status;o.timeline.push({status:req.body.status,at:new Date()});if(req.body.trackingId)o.trackingId=req.body.trackingId;if(req.body.courier)o.courier=req.body.courier;await o.save();await Notification.create({user:o.user,type:'ORDER',title:`Order ${req.body.status}`,message:`${o.orderNumber} is now ${req.body.status}`,link:'/orders.html'});await audit(req,'ORDER_STATUS','Order',o._id,null,{status:o.status,trackingId:o.trackingId,courier:o.courier});res.json(o)});
router.get('/users',async(req,res)=>res.json(await User.find().select('-password').sort({createdAt:-1}).limit(500)));
router.get('/coupons',async(req,res)=>res.json(await Coupon.find().sort({createdAt:-1})));
router.post('/coupons',async(req,res)=>{try{res.status(201).json(await Coupon.create(req.body))}catch(e){res.status(400).json({message:e.message})}});
router.delete('/coupons/:id',async(req,res)=>{await Coupon.findByIdAndDelete(req.params.id);res.json({message:'Deleted'})});
router.get('/banners',async(req,res)=>res.json(await Banner.find().sort({position:1})));
router.post('/banners',async(req,res)=>res.status(201).json(await Banner.create(req.body)));
router.patch('/banners/:id',async(req,res)=>res.json(await Banner.findByIdAndUpdate(req.params.id,req.body,{new:true})));
router.delete('/banners/:id',async(req,res)=>{await Banner.findByIdAndDelete(req.params.id);res.json({message:'Deleted'})});
router.get('/returns',async(req,res)=>res.json(await ReturnRequest.find().populate('order','orderNumber total').populate('user','name email').sort({createdAt:-1})));
router.patch('/returns/:id',async(req,res)=>{const rr=await ReturnRequest.findByIdAndUpdate(req.params.id,{$set:{status:req.body.status,adminNote:req.body.adminNote||''}},{new:true});if(!rr)return res.status(404).json({message:'Not found'});await Notification.create({user:rr.user,type:'RETURN',title:'Return request updated',message:`Return status: ${rr.status}`,link:'/profile.html'});res.json(rr)});
router.get('/support',async(req,res)=>res.json(await SupportTicket.find().populate('user','name email').populate('order','orderNumber status total paymentMethod paymentStatus items').sort({updatedAt:-1})));
router.post('/support/:id/reply',async(req,res)=>{const t=await SupportTicket.findById(req.params.id);if(!t)return res.status(404).json({message:'Not found'});t.messages.push({sender:req.user._id,role:'admin',message:req.body.message,at:new Date()});t.status=req.body.status||'IN_PROGRESS';await t.save();res.json(t)});
router.get('/inventory',async(req,res)=>res.json(await Inventory.find().populate('product','name sku').sort({createdAt:-1}).limit(300)));
router.get('/categories',async(req,res)=>res.json(await Category.find().sort({name:1})));
router.post('/categories',async(req,res)=>res.status(201).json(await Category.create(req.body)));
router.get('/brands',async(req,res)=>res.json(await Brand.find().sort({name:1})));
router.post('/brands',async(req,res)=>res.status(201).json(await Brand.create(req.body)));
router.get('/products-export.csv',async(req,res)=>{const rows=await Product.find({deletedAt:{$exists:false}}).lean();const esc=v=>'\"'+String(v??'').replaceAll('\"','\"\"')+'\"';const csv=['name,slug,sku,brand,category,price,mrp,stock',...rows.map(x=>[x.name,x.slug,x.sku,x.brand,x.category,x.price,x.mrp,x.stock].map(esc).join(','))].join('\n');res.type('text/csv').set('Content-Disposition','attachment; filename=shopverse-products.csv').send(csv)});
router.post('/products-bulk',async(req,res)=>{if(!Array.isArray(req.body.products))return res.status(400).json({message:'products array required'});let upserted=0;for(const x of req.body.products.slice(0,1000)){if(!x.sku||!x.slug||!x.name)continue;await Product.updateOne({sku:x.sku},{$set:x},{upsert:true,setDefaultsOnInsert:true});upserted++}res.json({upserted})});

router.get('/dashboard-v2',async(req,res)=>{const start=new Date();start.setHours(0,0,0,0);const [customers,products,orders,today,pending,delivered,cancelled,returns,revenue,low]=await Promise.all([User.countDocuments({role:'customer'}),Product.countDocuments({deletedAt:{$exists:false}}),Order.countDocuments(),Order.countDocuments({createdAt:{$gte:start}}),Order.countDocuments({status:{$in:['Payment Pending','Confirmed','Processing','Packed','Shipped','Out for Delivery']}}),Order.countDocuments({status:'Delivered'}),Order.countDocuments({status:'Cancelled'}),ReturnRequest.countDocuments(),Order.aggregate([{$match:{status:'Delivered'}},{$group:{_id:null,v:{$sum:'$total'}}}]),Product.countDocuments({stock:{$lte:5},deletedAt:{$exists:false}})]);res.json({customers,products,orders,todayOrders:today,pending,delivered,cancelled,returns,totalRevenue:revenue[0]?.v||0,lowStock:low})});


router.get('/product-chats',async(req,res)=>{const rows=await ProductChat.find().populate('user','name email mobile status').populate('product','name slug sku price images').sort({lastMessageAt:-1}).limit(500);res.json(rows)});
router.patch('/product-chats/:id/read',async(req,res)=>{const x=await ProductChat.findByIdAndUpdate(req.params.id,{unreadForAdmin:false},{new:true});if(!x)return res.status(404).json({message:'Chat not found'});res.json({ok:true})});
router.post('/product-chats/:id/reply',async(req,res)=>{const text=String(req.body.text||'').trim();if(!text)return res.status(400).json({message:'Message required'});const x=await ProductChat.findById(req.params.id);if(!x)return res.status(404).json({message:'Chat not found'});x.messages.push({sender:req.user._id,senderRole:'admin',text,at:new Date()});x.status=req.body.status==='RESOLVED'?'RESOLVED':'OPEN';x.unreadForAdmin=false;x.unreadForCustomer=true;x.lastMessageAt=new Date();await x.save();await Notification.create({user:x.user,type:'SUPPORT',title:'Admin replied about your product',message:text.slice(0,120),link:'/product-details.html'});res.json(x)});

module.exports=router;
