const router=require('express').Router();
const crypto=require('crypto');
const {auth,role}=require('../middleware/auth');
const Product=require('../models/Product');const Order=require('../models/Order');const User=require('../models/User');
const GiftCard=require('../models/GiftCard');const ProductChat=require('../models/ProductChat');const ProductQuestion=require('../models/ProductQuestion');const Alert=require('../models/AlertSubscription');const FlashSale=require('../models/FlashSale');const AuditLog=require('../models/AuditLog');const SearchEvent=require('../models/SearchEvent');const Refund=require('../models/Refund');const ReturnRequest=require('../models/ReturnRequest');const Notification=require('../models/Notification');const Wallet=require('../models/WalletTransaction');
const adminPermission=require('../middleware/adminPermission');const audit=require('../utils/audit');const cashfree=require('../services/cashfree');

router.get('/flash-sales',async(req,res)=>{const now=new Date();const rows=await FlashSale.find({active:true,startAt:{$lte:now},endAt:{$gte:now}}).populate('products.product','name slug images price mrp stock');res.json(rows)});
router.get('/questions/:productId',async(req,res)=>res.json(await ProductQuestion.find({product:req.params.productId,approved:true}).populate('user','name').populate('answers.user','name').sort({createdAt:-1})));
router.post('/search-event',async(req,res)=>{try{const q=String(req.body.query||'').trim().slice(0,100);if(!q)return res.json({ok:true});await SearchEvent.create({query:q,results:Number(req.body.results||0),sessionId:String(req.body.sessionId||'')});res.json({ok:true})}catch(e){res.json({ok:true})}});

router.get('/pincode/:pincode',async(req,res)=>{const pin=String(req.params.pincode||'').trim();if(!/^[1-9][0-9]{5}$/.test(pin))return res.status(400).json({message:'Enter a valid 6-digit Indian PIN code'});try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),5000);const r=await fetch('https://api.postalpincode.in/pincode/'+encodeURIComponent(pin),{signal:controller.signal,headers:{'User-Agent':'ShopVerse/1.0'}});clearTimeout(timer);if(!r.ok)throw new Error('PIN service unavailable');const data=await r.json();const first=Array.isArray(data)?data[0]:null;const offices=first?.PostOffice||[];if(!offices.length)return res.status(404).json({message:'PIN code not found in India Post directory'});const normalized=offices.map(o=>({name:o.Name||'',branchType:o.BranchType||'',deliveryStatus:o.DeliveryStatus||'',district:o.District||'',division:o.Division||'',region:o.Region||'',state:o.State||'',country:o.Country||'India'}));res.json({valid:true,pincode:pin,city:normalized[0].District||normalized[0].Region||'',district:normalized[0].District||'',state:normalized[0].State||'',country:'India',offices:normalized});}catch(e){res.status(503).json({message:'PIN lookup service is temporarily unavailable. Please try again.'})}});
router.get('/recommendations/:productId',async(req,res)=>{const p=await Product.findById(req.params.productId);if(!p)return res.status(404).json({message:'Product not found'});const items=await Product.find({_id:{$ne:p._id},$or:[{category:p.category},{brand:p.brand}],stock:{$gt:0}}).sort({bestSeller:-1,rating:-1}).limit(12);res.json(items)});

router.use(auth);

router.get('/product-chat/:productId',async(req,res)=>{let x=await ProductChat.findOne({product:req.params.productId,user:req.user._id}).populate('product','name slug sku price images');if(!x)return res.json(null);if(x.unreadForCustomer){x.unreadForCustomer=false;await x.save()}res.json(x)});
router.post('/product-chat/:productId/messages',async(req,res)=>{const text=String(req.body.text||'').trim();if(!text)return res.status(400).json({message:'Message required'});if(text.length>2000)return res.status(400).json({message:'Message is too long'});const product=await Product.findById(req.params.productId).select('_id');if(!product)return res.status(404).json({message:'Product not found'});let x=await ProductChat.findOne({product:product._id,user:req.user._id});if(!x)x=new ProductChat({product:product._id,user:req.user._id,messages:[]});x.messages.push({sender:req.user._id,senderRole:'customer',text,at:new Date()});x.status='OPEN';x.unreadForAdmin=true;x.unreadForCustomer=false;x.lastMessageAt=new Date();await x.save();res.status(201).json(x)});

router.post('/questions/:productId',async(req,res)=>{const q=await ProductQuestion.create({product:req.params.productId,user:req.user._id,question:req.body.question});res.status(201).json(q)});
router.post('/questions/:id/answer',role('admin'),async(req,res)=>{const q=await ProductQuestion.findById(req.params.id);if(!q)return res.status(404).json({message:'Question not found'});q.answers.push({user:req.user._id,role:'admin',text:req.body.text});await q.save();res.json(q)});
router.post('/alerts/:productId',async(req,res)=>{const type=String(req.body.type||'BACK_IN_STOCK').toUpperCase();const a=await Alert.findOneAndUpdate({user:req.user._id,product:req.params.productId,type},{targetPrice:req.body.targetPrice,active:true},{new:true,upsert:true,setDefaultsOnInsert:true});res.status(201).json(a)});
router.get('/alerts',async(req,res)=>res.json(await Alert.find({user:req.user._id}).populate('product','name slug price stock images')));
router.delete('/alerts/:id',async(req,res)=>{await Alert.deleteOne({_id:req.params.id,user:req.user._id});res.json({message:'Alert removed'})});
router.post('/recently-viewed/:productId',async(req,res)=>{await User.updateOne({_id:req.user._id},{$pull:{recentlyViewed:{product:req.params.productId}}});await User.updateOne({_id:req.user._id},{$push:{recentlyViewed:{$each:[{product:req.params.productId,at:new Date()}],$position:0,$slice:20}}});res.json({ok:true})});
router.get('/recently-viewed',async(req,res)=>{const u=await User.findById(req.user._id).populate('recentlyViewed.product');res.json((u.recentlyViewed||[]).map(x=>x.product).filter(Boolean))});
router.post('/gift-cards/redeem',async(req,res)=>{const code=String(req.body.code||'').toUpperCase();const g=await GiftCard.findOne({code,active:true});if(!g||g.balance<=0||(g.expiresAt&&g.expiresAt<new Date()))return res.status(400).json({message:'Invalid or expired gift card'});const amount=Math.min(g.balance,Math.max(0,Number(req.body.amount||g.balance)));g.balance-=amount;g.redemptions.push({user:req.user._id,amount,at:new Date()});await g.save();await User.updateOne({_id:req.user._id},{$inc:{walletBalance:amount}});await Wallet.create({user:req.user._id,type:'CREDIT',amount,description:`Gift card ${g.code}`});res.json({credited:amount,balance:g.balance})});
router.post('/wallet/redeem-points',async(req,res)=>{const points=Math.max(0,Math.floor(Number(req.body.points||0)));const u=await User.findById(req.user._id);if(points<100||u.loyaltyPoints<points)return res.status(400).json({message:'Minimum 100 points and sufficient balance required'});const amount=Math.floor(points/100)*10;u.loyaltyPoints-=Math.floor(points/100)*100;u.walletBalance+=amount;await u.save();await Wallet.create({user:u._id,type:'CREDIT',amount,description:`Redeemed ${Math.floor(points/100)*100} loyalty points`});res.json({walletBalance:u.walletBalance,loyaltyPoints:u.loyaltyPoints,credited:amount})});
router.get('/invoice/:orderId',async(req,res)=>{const o=await Order.findOne({_id:req.params.orderId,user:req.user._id});if(!o)return res.status(404).json({message:'Order not found'});res.json({invoiceNumber:`INV-${o.orderNumber}`,issuedAt:o.createdAt,seller:'ShopVerse Marketplace',order:o})});
router.post('/orders/:id/reorder',async(req,res)=>{const o=await Order.findOne({_id:req.params.id,user:req.user._id});if(!o)return res.status(404).json({message:'Order not found'});const u=await User.findById(req.user._id);for(const x of o.items){const p=await Product.findById(x.product);if(p&&p.stock>0&&!u.cart.some(c=>String(c.product)===String(p._id)))u.cart.push({product:p._id,qty:Math.min(x.qty,p.stock)});}await u.save();res.json({message:'Available items added to cart'})});
router.get('/delivery/:pincode',async(req,res)=>{const pin=String(req.params.pincode);if(!/^\d{6}$/.test(pin))return res.status(400).json({message:'Invalid PIN code'});res.json({serviceable:true,cod:true,estimatedDays:pin.startsWith('1')||pin.startsWith('2')?3:5,shipping:79})});


router.get('/admin/audit',role('admin'),adminPermission('analytics'),async(req,res)=>res.json(await AuditLog.find().populate('actor','name email').sort({createdAt:-1}).limit(500)));
router.get('/admin/search-analytics',role('admin'),adminPermission('analytics'),async(req,res)=>{const top=await SearchEvent.aggregate([{$group:{_id:{$toLower:'$query'},searches:{$sum:1},zero:{$sum:{$cond:[{$eq:['$results',0]},1,0]}}}},{$sort:{searches:-1}},{$limit:30}]);res.json(top)});
router.get('/admin/flash-sales',role('admin'),adminPermission('flashsales'),async(req,res)=>res.json(await FlashSale.find().populate('products.product','name sku').sort({createdAt:-1})));
router.post('/admin/flash-sales',role('admin'),adminPermission('flashsales'),async(req,res)=>{const x=await FlashSale.create(req.body);await audit(req,'CREATE_FLASH_SALE','FlashSale',x._id,null,x.toObject());res.status(201).json(x)});
router.patch('/admin/flash-sales/:id',role('admin'),adminPermission('flashsales'),async(req,res)=>{const before=await FlashSale.findById(req.params.id);const x=await FlashSale.findByIdAndUpdate(req.params.id,req.body,{new:true});await audit(req,'UPDATE_FLASH_SALE','FlashSale',x?._id,before?.toObject(),x?.toObject());res.json(x)});
router.delete('/admin/flash-sales/:id',role('admin'),adminPermission('flashsales'),async(req,res)=>{await FlashSale.findByIdAndDelete(req.params.id);res.json({message:'Deleted'})});
router.get('/admin/gift-cards',role('admin'),async(req,res)=>res.json(await GiftCard.find().sort({createdAt:-1})));
router.post('/admin/gift-cards',role('admin'),async(req,res)=>{const balance=Number(req.body.balance||req.body.initialBalance||0);const code=String(req.body.code||('SVG'+crypto.randomBytes(5).toString('hex'))).toUpperCase();const x=await GiftCard.create({code,initialBalance:balance,balance,expiresAt:req.body.expiresAt,createdBy:req.user._id});await audit(req,'CREATE_GIFT_CARD','GiftCard',x._id,null,x.toObject());res.status(201).json(x)});
router.patch('/admin/users/:id/status',role('admin'),async(req,res)=>{const status=String(req.body.status||'ACTIVE').toUpperCase();if(!['ACTIVE','SUSPENDED'].includes(status))return res.status(400).json({message:'Invalid status'});const before=await User.findById(req.params.id).lean();const u=await User.findByIdAndUpdate(req.params.id,{status},{new:true}).select('-password');await audit(req,'USER_STATUS','User',u?._id,before,u?.toObject());res.json(u)});
router.patch('/admin/users/:id/admin-role',role('admin'),async(req,res)=>{const u=await User.findOneAndUpdate({_id:req.params.id,role:'admin'},{adminRole:req.body.adminRole},{new:true,runValidators:true}).select('-password');if(!u)return res.status(404).json({message:'Admin not found'});res.json(u)});
router.post('/admin/refunds/:returnId',role('admin'),adminPermission('refunds'),async(req,res)=>{const rr=await ReturnRequest.findById(req.params.returnId);if(!rr)return res.status(404).json({message:'Return not found'});const amount=Number(req.body.amount||rr.refundAmount||0);const method=req.body.method==='WALLET'?'WALLET':'ORIGINAL';const order=await Order.findById(rr.order);let providerRefundId='';let status=method==='WALLET'?'SUCCESS':'PROCESSING';if(method==='ORIGINAL'){if(!order||order.paymentMethod!=='CASHFREE'||order.paymentStatus!=='PAID')return res.status(400).json({message:'Original-method refund requires a paid Cashfree order'});if(!cashfree.configured())return res.status(400).json({message:'Cashfree is not configured'});const refundId='SVRF'+Date.now()+crypto.randomBytes(2).toString('hex').toUpperCase();const cf=await cashfree.createRefund(order.cashfreeOrderId||String(order._id),{refund_amount:amount,refund_id:refundId,refund_note:rr.reason||'ShopVerse return refund'});providerRefundId=cf.cf_refund_id||cf.refund_id||refundId;status=['SUCCESS','PROCESSED'].includes(String(cf.refund_status||'').toUpperCase())?'SUCCESS':'PROCESSING';}const ref=await Refund.create({order:rr.order,returnRequest:rr._id,user:rr.user,amount,method,providerRefundId,status,reason:rr.reason});if(method==='WALLET'){await User.updateOne({_id:rr.user},{$inc:{walletBalance:amount}});await Wallet.create({user:rr.user,type:'CREDIT',amount,description:'Order refund'});rr.status='REFUNDED';await rr.save();await Notification.create({user:rr.user,type:'REFUND',title:'Refund credited',message:`₹${amount} credited to ShopVerse Wallet`,link:'/profile.html'});}res.status(201).json(ref)});
router.get('/admin/refunds',role('admin'),async(req,res)=>res.json(await Refund.find().populate('order','orderNumber').populate('user','name email').sort({createdAt:-1})));
module.exports=router;
