const router=require('express').Router();const {auth}=require('../middleware/auth');const User=require('../models/User');const Product=require('../models/Product');
router.use(auth);
router.get('/cart',async(req,res)=>{const u=await User.findById(req.user._id).populate('cart.product');res.json(u.cart);});
router.post('/cart',async(req,res)=>{const {productId,qty=1,variant=''}=req.body;const p=await Product.findById(productId);if(!p||p.stock<qty)return res.status(400).json({message:'Product unavailable'});const u=await User.findById(req.user._id);const i=u.cart.findIndex(x=>String(x.product)===String(productId)&&x.variant===variant);if(i>=0)u.cart[i].qty=Math.max(1,Math.min(10,u.cart[i].qty+Number(qty)));else u.cart.push({product:productId,qty,variant});await u.save();res.json({message:'Added to cart',count:u.cart.length});});
router.patch('/cart/:productId',async(req,res)=>{const u=await User.findById(req.user._id);const i=u.cart.findIndex(x=>String(x.product)===req.params.productId);if(i<0)return res.status(404).json({message:'Not in cart'});u.cart[i].qty=Math.max(1,Math.min(10,Number(req.body.qty)||1));await u.save();res.json({message:'Updated'});});
router.delete('/cart/:productId',async(req,res)=>{const u=await User.findById(req.user._id);u.cart=u.cart.filter(x=>String(x.product)!==req.params.productId);await u.save();res.json({message:'Removed'});});
router.get('/wishlist',async(req,res)=>{const u=await User.findById(req.user._id).populate('wishlist');res.json(u.wishlist);});
router.post('/wishlist/:productId',async(req,res)=>{const u=await User.findById(req.user._id);const id=req.params.productId;if(!u.wishlist.some(x=>String(x)===id))u.wishlist.push(id);await u.save();res.json({message:'Wishlisted'});});
router.delete('/wishlist/:productId',async(req,res)=>{const u=await User.findById(req.user._id);u.wishlist=u.wishlist.filter(x=>String(x)!==req.params.productId);await u.save();res.json({message:'Removed'});});

router.get('/profile',async(req,res)=>{const u=await User.findById(req.user._id).select('-password').populate('wishlist');res.json(u)});
router.patch('/profile',async(req,res)=>{const allow=['name','mobile'];const data={};for(const k of allow)if(req.body[k]!==undefined)data[k]=req.body[k];const u=await User.findByIdAndUpdate(req.user._id,data,{new:true,runValidators:true}).select('-password');res.json(u)});
router.post('/addresses',async(req,res)=>{const pin=String(req.body.pincode||'');if(!/^[1-9][0-9]{5}$/.test(pin))return res.status(400).json({message:'Valid 6-digit Indian PIN code required'});if(!String(req.body.line1||'').trim()||!String(req.body.city||'').trim()||!String(req.body.state||'').trim())return res.status(400).json({message:'Complete address required'});const u=await User.findById(req.user._id);const data={...req.body,isDefault:!!req.body.isDefault};if(!u.addresses.length)data.isDefault=true;if(data.isDefault)u.addresses.forEach(x=>x.isDefault=false);u.addresses.push(data);await u.save();res.status(201).json(u.addresses)});
router.patch('/addresses/:id',async(req,res)=>{const u=await User.findById(req.user._id);const a=u.addresses.id(req.params.id);if(!a)return res.status(404).json({message:'Address not found'});if(req.body.isDefault===true)u.addresses.forEach(x=>x.isDefault=false);Object.assign(a,req.body);await u.save();res.json(u.addresses)});
router.patch('/addresses/:id/default',async(req,res)=>{const u=await User.findById(req.user._id);const a=u.addresses.id(req.params.id);if(!a)return res.status(404).json({message:'Address not found'});u.addresses.forEach(x=>x.isDefault=String(x._id)===String(a._id));await u.save();res.json(u.addresses)});
router.delete('/addresses/:id',async(req,res)=>{const u=await User.findById(req.user._id);const a=u.addresses.id(req.params.id);if(!a)return res.status(404).json({message:'Address not found'});a.deleteOne();await u.save();res.json(u.addresses)});

module.exports=router;
